CREATE TABLE users (
  id SERIAL NOT NULL PRIMARY KEY,
  pseudo TEXT NOT NULL UNIQUE,
  first_name TEXT,
  last_name TEXT,
  email TEXT NOT NULL,
  google_id TEXT,
  password TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  -- add updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
